"""API integration tests for assistive vision inference service."""

from __future__ import annotations

from dataclasses import replace

from fastapi.testclient import TestClient
import pytest

from api import main as main_module
from api.main import app, rate_limiter

client = TestClient(app)


# Generated by GitHub Copilot
def _override_settings(monkeypatch, **changes):
    """Apply temporary runtime setting overrides for API security tests."""

    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, **changes))


@pytest.fixture(autouse=True)
def reset_runtime_state(monkeypatch):
    """Reset limiter and settings between tests for deterministic outcomes."""

    rate_limiter.clear()
    _override_settings(monkeypatch, api_key="", rate_limit_per_minute=600)

    yield

    rate_limiter.clear()


def test_health_endpoint_is_public() -> None:
    """Health endpoint should remain public regardless of auth settings."""

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_infer_frame_contract_returns_detections_and_messages() -> None:
    """Infer endpoint should return normalized frame payload with guidance messages."""

    response = client.post(
        "/infer-frame",
        json={
            "frame_id": "f-1",
            "objects": [
                {
                    "label": "person",
                    "confidence": 0.91,
                    "bbox": [40, 30, 170, 250],
                }
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["frame_id"] == "f-1"
    assert payload["detections"]
    assert payload["messages"]


def test_infer_frame_requires_api_key_when_configured(monkeypatch) -> None:
    """Infer endpoint should require API key when runtime key is configured."""

    _override_settings(monkeypatch, api_key="secret-key")

    unauthorized = client.post(
        "/infer-frame",
        json={"frame_id": "f-2", "objects": []},
    )
    assert unauthorized.status_code == 401

    authorized = client.post(
        "/infer-frame",
        headers={"X-API-Key": "secret-key"},
        json={"frame_id": "f-2", "objects": []},
    )
    assert authorized.status_code == 200


def test_infer_frame_rate_limit_returns_429(monkeypatch) -> None:
    """Infer endpoint should return 429 once per-minute client quota is exceeded."""

    _override_settings(monkeypatch, rate_limit_per_minute=1)

    first = client.post(
        "/infer-frame",
        json={"frame_id": "f-3", "objects": []},
    )
    assert first.status_code == 200

    second = client.post(
        "/infer-frame",
        json={"frame_id": "f-4", "objects": []},
    )
    assert second.status_code == 429


def test_health_remains_public_with_api_key(monkeypatch) -> None:
    """Health endpoint should stay unauthenticated for infrastructure probes."""

    _override_settings(monkeypatch, api_key="secret-key")

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["service"] == "assistive-vision"
