"""API integration tests for assistive vision inference service."""

from __future__ import annotations

from dataclasses import replace

from fastapi.testclient import TestClient
import pytest

from api import main as main_module
from api.main import app, rate_limiter

client = TestClient(app)


def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized API error contract fields."""

    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


# Generated by GitHub Copilot
def _override_settings(monkeypatch, **changes):
    """Apply temporary runtime setting overrides for API security tests."""

    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, **changes))


@pytest.fixture(autouse=True)
def reset_runtime_state(monkeypatch):
    """Reset limiter and settings between tests for deterministic outcomes."""

    rate_limiter.clear()
    _override_settings(monkeypatch, api_key="", rate_limit_per_minute=600)

    yield

    rate_limiter.clear()


def test_health_endpoint_is_public() -> None:
    """Health endpoint should remain public regardless of auth settings."""

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_probe_alias_endpoints_return_runtime_state() -> None:
    """Readiness and probe aliases should be available for deployment checks."""

    ready = client.get("/ready")
    assert ready.status_code == 200
    assert ready.json()["status"] == "ready"

    health_alias = client.get("/healthz")
    assert health_alias.status_code == 200
    assert health_alias.json()["status"] == "ok"

    ready_alias = client.get("/readyz")
    assert ready_alias.status_code == 200
    assert ready_alias.json()["status"] == "ready"


def test_infer_frame_contract_returns_detections_and_messages() -> None:
    """Infer endpoint should return normalized frame payload with guidance messages."""

    response = client.post(
        "/infer-frame",
        json={
            "frame_id": "f-1",
            "objects": [
                {
                    "label": "person",
                    "confidence": 0.91,
                    "bbox": [40, 30, 170, 250],
                }
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["frame_id"] == "f-1"
    assert payload["detections"]
    assert payload["messages"]


def test_infer_frame_requires_api_key_when_configured(monkeypatch) -> None:
    """Infer endpoint should require API key when runtime key is configured."""

    _override_settings(monkeypatch, api_key="secret-key")

    unauthorized = client.post(
        "/infer-frame",
        json={"frame_id": "f-2", "objects": []},
    )
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.post(
        "/infer-frame",
        headers={"X-API-Key": "secret-key"},
        json={"frame_id": "f-2", "objects": []},
    )
    assert authorized.status_code == 200


def test_infer_frame_rate_limit_returns_429(monkeypatch) -> None:
    """Infer endpoint should return 429 once per-minute client quota is exceeded."""

    _override_settings(monkeypatch, rate_limit_per_minute=1)

    first = client.post(
        "/infer-frame",
        json={"frame_id": "f-3", "objects": []},
    )
    assert first.status_code == 200

    second = client.post(
        "/infer-frame",
        json={"frame_id": "f-4", "objects": []},
    )
    _assert_error_contract(
        second,
        expected_status=429,
        expected_code="rate_limited",
        expected_message="rate_limited",
    )
    assert second.headers.get("Retry-After") == "60"


def test_health_remains_public_with_api_key(monkeypatch) -> None:
    """Health endpoint should stay unauthenticated for infrastructure probes."""

    _override_settings(monkeypatch, api_key="secret-key")

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["service"] == "assistive-vision"

    ready_response = client.get("/ready")
    assert ready_response.status_code == 200
    assert ready_response.json()["status"] == "ready"


def test_phase1_error_contract_response() -> None:
    """Invalid payload should return normalized validation error payload."""

    response = client.post(
        "/infer-frame",
        json={"frame_id": "", "objects": []},
    )
    _assert_error_contract(
        response,
        expected_status=422,
        expected_code="validation_error",
        expected_message="request_validation_failed",
        expect_details=True,
    )


def test_error_responses_include_request_and_security_headers(monkeypatch) -> None:
    """Error responses should carry request tracing and baseline security headers."""

    _override_settings(monkeypatch, api_key="header-secret")
    response = client.post(
        "/infer-frame",
        json={"frame_id": "f-sec", "objects": []},
    )

    assert response.status_code == 401
    assert response.headers.get("X-Request-ID")
    assert response.headers.get("X-Content-Type-Options") == "nosniff"
    assert response.headers.get("X-Frame-Options") == "DENY"
