from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any


@dataclass
class Detection:
    track_id: int
    label: str
    confidence: float
    bbox: list[float]
    distance_m: float


# Generated by GitHub Copilot
class MockYoloV3Detector:
    """Deterministic detector adapter for portability without GPU dependencies."""

    def detect(self, objects: list[dict[str, Any]]) -> list[dict[str, Any]]:
        output = []
        for item in objects:
            label = str(item.get("label", "unknown"))
            confidence = float(item.get("confidence", 0.0))
            bbox = item.get("bbox", [0, 0, 0, 0])
            if len(bbox) != 4:
                bbox = [0, 0, 0, 0]
            output.append(
                {
                    "label": label,
                    "confidence": max(0.0, min(1.0, confidence)),
                    "bbox": [float(value) for value in bbox],
                }
            )
        return output


# Generated by GitHub Copilot
class SimpleTracker:
    """Maintains object identities with nearest-centroid assignment."""

    def __init__(self) -> None:
        self._last_centroids: dict[int, tuple[float, float]] = {}
        self._next_id = 1

    @staticmethod
    def _centroid(bbox: list[float]) -> tuple[float, float]:
        x1, y1, x2, y2 = bbox
        return ((x1 + x2) / 2.0, (y1 + y2) / 2.0)

    def assign(self, detections: list[dict[str, Any]]) -> list[dict[str, Any]]:
        assigned: list[dict[str, Any]] = []
        consumed_ids: set[int] = set()

        for detection in detections:
            centroid = self._centroid(detection["bbox"])
            chosen_id = None
            chosen_distance = float("inf")

            for track_id, previous in self._last_centroids.items():
                if track_id in consumed_ids:
                    continue
                distance = math.dist(centroid, previous)
                if distance < chosen_distance and distance < 120:
                    chosen_id = track_id
                    chosen_distance = distance

            if chosen_id is None:
                chosen_id = self._next_id
                self._next_id += 1

            consumed_ids.add(chosen_id)
            self._last_centroids[chosen_id] = centroid

            enriched = dict(detection)
            enriched["track_id"] = chosen_id
            assigned.append(enriched)

        return assigned


# Generated by GitHub Copilot
def estimate_distance_m(bbox: list[float], frame_height: float = 480.0) -> float:
    """Approximate relative distance from box height for guidance prioritization."""

    _, y1, _, y2 = bbox
    box_height = max(1.0, y2 - y1)
    normalized = min(1.0, box_height / frame_height)
    distance = max(0.4, 6.0 * (1.0 - normalized))
    return round(distance, 2)


# Generated by GitHub Copilot
def build_guidance_messages(detections: list[Detection]) -> list[str]:
    """Generate human-friendly feedback messages from tracked detections."""

    if not detections:
        return ["No nearby obstacles detected."]

    sorted_items = sorted(detections, key=lambda item: item.distance_m)
    messages = []

    for item in sorted_items[:3]:
        if item.distance_m <= 1.5:
            messages.append(f"Warning: {item.label} very close at {item.distance_m} meters.")
        elif item.distance_m <= 3.0:
            messages.append(f"Caution: {item.label} ahead at {item.distance_m} meters.")
        else:
            messages.append(f"Info: {item.label} detected at {item.distance_m} meters.")

    return messages


# Generated by GitHub Copilot
class AssistiveVisionPipeline:
    """Composes detector, tracker, and guidance modules into one frame pipeline."""

    def __init__(self) -> None:
        self.detector = MockYoloV3Detector()
        self.tracker = SimpleTracker()

    def process_frame(self, objects: list[dict[str, Any]]) -> dict[str, Any]:
        raw = self.detector.detect(objects)
        tracked = self.tracker.assign(raw)

        detections: list[Detection] = []
        for item in tracked:
            detections.append(
                Detection(
                    track_id=int(item["track_id"]),
                    label=item["label"],
                    confidence=float(item["confidence"]),
                    bbox=item["bbox"],
                    distance_m=estimate_distance_m(item["bbox"]),
                )
            )

        messages = build_guidance_messages(detections)

        return {
            "detections": [
                {
                    "track_id": detection.track_id,
                    "label": detection.label,
                    "confidence": detection.confidence,
                    "bbox": detection.bbox,
                    "distance_m": detection.distance_m,
                }
                for detection in detections
            ],
            "messages": messages,
        }
