from __future__ import annotations

from dataclasses import dataclass
import os
from threading import Lock
from time import monotonic
from typing import Annotated, Any
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response
from pydantic import BaseModel, Field

from src.pipeline import AssistiveVisionPipeline


# Generated by GitHub Copilot
@dataclass(frozen=True)
class Settings:
    """Runtime settings for optional API auth and request throttling."""

    api_key: str
    rate_limit_per_minute: int


# Generated by GitHub Copilot
class InMemoryRateLimiter:
    """Simple per-client fixed-window limiter for write-heavy endpoints."""

    def __init__(self, window_seconds: int = 60) -> None:
        """Initialize in-memory event storage for fixed-window throttling."""

        self.window_seconds = window_seconds
        self._events: dict[str, list[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return True when the client key is still within rate limits."""

        now = monotonic()
        window_start = now - self.window_seconds

        with self._lock:
            timeline = [timestamp for timestamp in self._events.get(key, []) if timestamp >= window_start]
            if len(timeline) >= limit:
                self._events[key] = timeline
                return False
            timeline.append(now)
            self._events[key] = timeline
        return True

    def clear(self) -> None:
        """Clear limiter state; intended for tests and maintenance operations."""

        with self._lock:
            self._events.clear()


# Generated by GitHub Copilot
def _load_settings() -> Settings:
    """Load service settings from environment variables with safe defaults."""

    return Settings(
        api_key=os.getenv("ASSISTIVE_API_KEY", "").strip(),
        rate_limit_per_minute=int(os.getenv("ASSISTIVE_RATE_LIMIT_PER_MINUTE", "600")),
    )


# Generated by GitHub Copilot
def _require_api_key(
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    """Enforce optional API key auth on protected endpoints."""

    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="Unauthorized")


# Generated by GitHub Copilot
def _enforce_rate_limit(request: Request) -> None:
    """Reject requests that exceed per-client in-memory rate limits."""

    client_key = request.client.host if request.client and request.client.host else "unknown"
    if not rate_limiter.allow(client_key, settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")


class FrameRequest(BaseModel):
    """Payload schema for one frame inference request."""

    frame_id: str = Field(min_length=1, max_length=120)
    objects: list[dict[str, Any]] = Field(default_factory=list, max_length=200)


app = FastAPI(title="object-detection-audio-feedback-assistive", version="0.1.0")
pipeline = AssistiveVisionPipeline()
settings = _load_settings()
rate_limiter = InMemoryRateLimiter(window_seconds=60)
AuthDep = Annotated[None, Depends(_require_api_key)]


@app.middleware("http")
async def add_request_metadata(request: Request, call_next: Any) -> Response:
    """Attach request id and baseline secure response headers."""

    request_id = request.headers.get("X-Request-ID") or str(uuid4())
    response = await call_next(request)
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    return response


@app.get("/health")
def health() -> dict[str, str]:
    """Return lightweight health details for probes and uptime checks."""

    return {
        "status": "ok",
        "service": "assistive-vision",
    }


@app.post("/infer-frame")
def infer_frame(payload: FrameRequest, request: Request, _: AuthDep = None) -> dict[str, Any]:
    """Run detection/tracking pipeline for one frame payload."""

    _enforce_rate_limit(request)

    result = pipeline.process_frame(payload.objects)
    return {
        "frame_id": payload.frame_id,
        **result,
    }
